# source = ~/.config/hypr/source/keyboard.conf

gesture = 3, horizontal, workspace                 # 3-finger swipe to switch workspaces
gesture = 3, up,    mod: SUPER, fullscreen         # SUPER+3-finger up = fullscreen
gesture = 3, down,  mod: ALT,   close              # ALT+3-finger down = close window
gesture = 4, pinch, mod: SUPER, scale: 1.5, resize # 4-finger pinch to resize window

input {
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        scroll_factor = 0.25
    }

    sensitivity = 0
}
