# Fabric
layerrule = no_anim on, match:namespace fabric
# layerrule = ignorealpha 0.75, fabric
# blurls=fabric

windowrule = float on, match:class ^(org.gnome.Calculator)$

# Picture-in-picture
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = move 1492 839, match:title ^(Picture-in-Picture)$
windowrule = size 427 240, match:title (Picture-in-Picture)$
windowrule = pin on, match:title (Picture-in-Picture)$

# Kitty floating
windowrule = float on, match:class ^(kitty-floating)$
windowrule = float on, match:class (ghostty-floating)$

# Existing feh rule (already floating)
windowrule = float on, match:class (feh)$
windowrule = size 800 600, match:class ^(feh)$
# windowrulev2 = move 760 390, class:^(feh)$

# Selection (slurp, grimblast, etc.)
layerrule= no_anim on, match:tag selection

# Idle inhibit when in fullscreen
windowrule = idle_inhibit fullscreen, match:fullscreen_state_client 2

# Audacious
windowrule = rounding 0, no_anim on, match:class ^Audacious$
windowrule = rounding 0, no_anim on, match:class Audacious$
windowrule = rounding 0, no_anim on, match:class Audacious$
