[manager]
cwd = { fg = "#e7bdb7", bold=true}

hovered         = { fg = "#ffdad5", bg = "#73342c" }
preview_hovered = { underline = true, bold=true }


[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#ffdad5", bg = "#73342c" }

# Mode
mode_normal = { fg = "#561e18",   bg = "#ffb4aa", bold = true }
mode_select = { fg = "#442926", bg = "#e7bdb7", bold = true }
mode_unset  = { fg = "#3f2e04",  bg = "#dfc38c", bold = true }

[which]
mask            = { bg = "#271d1c" }
cand            = { fg = "#ffb4aa" }
desc            = { fg = "#e7bdb7" }
separator       = "  "
separator_style = { fg = "#dfc38c" }

[filetype]
rules = [
	# Images
	{ mime = "image/*", fg = "#e7bdb7" },

	# Videos
	{ mime = "video/*", fg = "#dfc38c" },
	{ mime = "audio/*", fg = "#dfc38c" },

	# Archives
	{ mime = "application/zip",             fg = "#ffb4ab" },
	{ mime = "application/gzip",            fg = "#ffb4ab" },
	{ mime = "application/x-tar",           fg = "#ffb4ab" },
	{ mime = "application/x-bzip",          fg = "#ffb4ab" },
	{ mime = "application/x-bzip2",         fg = "#ffb4ab" },
	{ mime = "application/x-7z-compressed", fg = "#ffb4ab" },
	{ mime = "application/x-rar",           fg = "#ffb4ab" },

	# Fallback
	{ name = "*", fg = "#ffb4aa", bold=true },
	{ name = "*/", fg = "#e7bdb7", bold=true }
]
