$wallpaper = /home/superb00y/Pictures/wals/wallhaven-o5zw57.png
$background = 0f1416
$foreground = dee3e6

$primary = 87d1ea
$secondary = b3cad4
$tertiary = c1c4eb
$surface = 0f1416
$surface_bright = 343a3c
$outline = 899296
$error = ff5945
