$wallpaper = /home/superb00y/Pictures/wallhaven-x6vjev.jpg
$background = 1a120e
$foreground = f0dfd8

$primary = ffb692
$secondary = e6beac
$tertiary = d0c890
$surface = 1a120e
$surface_bright = 423732
$outline = a08d85
$error = ff5945
