inherits = "ayu_dark"
"ui.background" ={}

"markup.heading" = { modifiers = ["hidden"] }
"markup.heading.1" = { fg = "black", bg = "light-red", modifiers = ["bold"] }
"markup.heading.2" = { fg = "black", bg = "light-green", modifiers = ["bold"] }
"markup.heading.3" = { fg = "black", bg = "light-yellow", modifiers = ["bold"] }
"markup.heading.4" = { fg = "black", bg = "light-blue", modifiers = ["bold"] }
"markup.heading.5" = { fg = "black", bg = "light-magenta", modifiers = ["bold"] }
"markup.heading.6" = { fg = "black", bg = "light-cyan", modifiers = ["bold"] }


